### ISSUE TITLE
User mention

### ISSUE THREAD

**Issue by sta-szek** [edge/simple-slack-notify#11]
Hi guys,

is it possible somehow to mention user in slack that is responsible for workflow invocation?
I tried to use `failure_text: "${env.GITHUB_WORKFLOW} (${env.GITHUB_RUN_NUMBER}) build failed @${{ github.actor }} :rocket:"`

but the message looks like that:
![Screenshot 2021-05-19 at 16 50 33](https://user-images.githubusercontent.com/6240704/118834197-54c07f80-b8c2-11eb-91bd-e3307b3ba7c5.png)

**Comment by annybs** [comment]
I believe you should be able to use the syntax `<@abcd>` to mention a user: https://api.slack.com/reference/surfaces/formatting#mentioning-users

This isn't strictly an issue with our action, so I'm closing this issue, but thanks for prompting me to look into it because I've wondered about it too!
