### ISSUE TITLE
Variables not propagated

### ISSUE THREAD

**Issue by patFish** [edge/simple-slack-notify#8]
The Messages provided by the Readme are not propagated or otherwise to forward to slack.
![image](https://user-images.githubusercontent.com/21482098/100339141-c4bc1000-2fd9-11eb-9fd4-ef00d0d1cbdb.png)
![image](https://user-images.githubusercontent.com/21482098/100339175-d1d8ff00-2fd9-11eb-8c51-8b4e43beaef1.png)
How do I enable this again?

**Comment by adamkdean** [comment]
Hi @patFish, which version are you using? `1.0.4` or `master` branch?

**Comment by adamkdean** [comment]
It looks like the recent changes may have been breaking. We're looking into this now and should have it fixed shortly.

**Comment by annybs** [comment]
@patFish I've just pushed a fix to master, please try it again.

**Comment by adamkdean** [comment]
I've tested this and it seems to be working. Closing the ticket but if you have any more issues @patFish please let us know.
